### ISSUE TITLE
how to run in the system of ubantu

### ISSUE THREAD

**Issue by WindHunter-Yang** [crownpku/text2vec#1]
I install spacy successfully,but it have the error --NameError: name 'spacy' is not defined
maybe the code that t2v = text2vec.text2vec(doc_list) have some problem, how to fill the doc_list

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    t2v = text2vec.text2vec('train/1.txt')
  File "/home/steven_yang/workspace/text2vec-master/text2vec.py", line 16, in __init__
    self.nlp, self.docs, self.docs_dict = self._preprocess(self.doc_list)
  File "/home/steven_yang/workspace/text2vec-master/text2vec.py", line 38, in _preprocess
    nlp  = spacy.load('en')
NameError: name 'spacy' is not defined

**Comment by Benjamin-3281** [comment]
This often does the trick for import problems:

sudo -H pip3 install spacy

**Comment by tamannashrma** [comment]
Showing an constant error of module is not callable?
**Code:**
import re
import heapq
import nltk
import numpy as np
import gensim, logging
from text import text2vec
f = open("D:\dataset\mahout-0.8\mahout-0.8_Corpus.txt")
doc_list = f.read()
#doc_list = re.split("\n\n", doc1)
t2v = text2vec(doc_list)
print(t2v)
PS: text is the file which contatin code of text2vec
 **output**:
import text2vec
  File "C:\Part 1 - Data Preprocessing\Data_Preprocessing\text2vec.py", line 16, in <module>
    t2v = text2vec.text2vec(doc_list)
TypeError: 'module' object is not callable
